---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  instanceProfile: {{ .Values.aws.defaultInstanceProfile }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.settings.clusterName }}
  tags:
    karpenter.sh/discovery: {{ .Values.settings.clusterName }}