---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
{{ toYaml .Values.nodePool.default.requirements | indent 8 }}      
  limits:
    cpu: 1000
  disruption:
{{ toYaml .Values.nodePool.default.disruption | indent 4 }}