apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uncs-deploy-dns.fullname" . }}
  labels:
    {{- include "uncs-deploy-dns.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "uncs-deploy-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uncs-deploy-dns.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountCustomName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          #command: ["/bin/bash", "-c"]
          #args: ["sleep 60m"] #{{ .Values.deployment.args }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: AWS_SSM_PARAMETER_ROLE_ARN
              value: "arn:aws:ssm:us-west-2:890013126756:parameter/INFRA_DEPLOY_ASSUME_ROLES"
            - name: AWS_SSM_PARAMETER_ZONES_ARN
              value: "arn:aws:ssm:us-west-2:890013126756:parameter/INFRA_DEPLOY_ROUTE53_ZONES"
            - name: AWS_REGION
              value: "us-west-2"
            - name: PORT_APP
              value: "9090"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
