config:
  name: ${APP_NAME}
  dockerImage: ${DOCKER_IMAGE}
  secretId: ${SECRET_ID}
  secretAgent: ${SECRET_AGENT}
  envName: ${ENV_NAME}
  awsRegion: ${AWS_REGION}
  tagVersion: ${TAG_VERSION}

deployment:
  replicas: 1
  args: ["source /shared/sm/config/envvars && /app/brikl-store-webserver"]
  nodeSelector: null

ingressHostMulti:
  enabled: false

ingress:
  host: null
  host2: null #optional
  class: nginx-public
  externalDnsEnabled: false

sa:
  enabled: true

volume:
  enabled: true
  size: 10Gi
  server: null
  path: null

sa:
  enabled: true
