config:
  name: ${APP_NAME}
  dockerImage: ${DOCKER_IMAGE}
  secretId: ${SECRET_ID}
  secretAgent: ${SECRET_AGENT}
  envName: ${ENV_NAME}
  awsRegion: ${AWS_REGION}
  tagVersion: ${TAG_VERSION}

ingressHostMulti:
  enabled: false

ingress:
  host: ${INGRESS_HOST}
  host2: ${INGRESS_HOST2} #optional
  class: ${INGRESS_CLASS}

sa:
  enabled: true