apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
spec:
  capacity:
    storage: {{ .Values.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.fileSystemId }}