apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.metadata.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:                                                                                                                                                                                                                           
  type: {{ .Values.parameters.type }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion }}
provisioner: {{ .Values.provisioner }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
