apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.name }}
  labels:
    app: {{ .Values.config.name }}
    env: {{ .Values.config.envName }}
    tag: {{ .Values.config.tagVersion }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.config.name }}
      tier: backend
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.name }}
        tier: backend
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/auth-path: 'auth/{{ .Values.secret.auth }}'
        vault.hashicorp.com/role: '{{ .Values.secret.role }}'
        vault.hashicorp.com/agent-inject-secret-config: '{{ .Values.secret.path }}'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ printf "{{- with secret \"%s\" -}}" .Values.secret.path }}
            {{`{{- range $key, $value := .Data.data }}`}}
            export {{`{{ $key }}`}}={{`{{ $value }}`}}
            {{`{{- end }}`}}
          {{`{{- end }}`}}      
    spec:
{{ if .Values.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 8 }}
{{ end }}
{{ if .Values.sa.enabled }}
      serviceAccountName: {{ .Values.config.name }}-sa
{{ end }}
      containers:
      - name: {{ .Values.config.name }}
        image: {{ .Values.config.dockerImage }}
        command: ["/bin/bash", "-c"]
        args: {{ .Values.deployment.args }}
        imagePullPolicy: Always
        {{ if .Values.deployment.timezone }}
        env:
          - name: TZ
            value: {{ .Values.deployment.timezone }}
        {{- end }}  
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
      {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | indent 10 }}
      {{- end }}
      {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | indent 10 }}
      {{- end}}
