{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.config.name }}-hpa
  labels:
    app: {{ .Values.config.name }}
    env: {{ .Values.config.envName }}
    tag: {{ .Values.config.tagVersion }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.config.name }}
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  minDelaySeconds: 300
{{- end -}}