{{- if .Values.secrets_sa.enabled -}}
# RBAC (service account + role + role binding)
## Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.config.name }}-sa
automountServiceAccountToken: true
---
## ClusterRole (update existing secret or create a new one, and create ingress)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.config.name }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["awscred"]
  verbs: ["get", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create"]
---
## ClusterRole Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.config.name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.config.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.config.name }}-sa
  namespace: {{ .Values.config.namespace }}
{{- end -}}