{{- if .Values.secrets_sa.enabled -}}
# RBAC (service account + role + role binding)
## Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.config.name }}-sa
{{- if .Values.secrets_sa.irsa_enabled -}}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets_sa.irsa_role_arn }}
{{- end -}}
automountServiceAccountToken: true
---
## Role (update existing secret or create a new one)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.config.name }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["awscred"]
  verbs: ["get", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]

---
## Role Binding
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.config.name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.config.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.config.name }}-sa
{{- end -}}