apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uncs-deploy-api.fullname" . }}
  labels:
    {{- include "uncs-deploy-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "uncs-deploy-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uncs-deploy-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountCustomName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DNS_API_URL
              value: "http://{{ .Values.customdeploy.dnsServicesName }}.{{ .Release.Namespace }}.svc.cluster.local:9090"
            - name: IRSA_API_URL
              value: "http://{{ .Values.customdeploy.irsaServiceName }}.{{ .Release.Namespace }}.svc.cluster.local:9090"
            - name: AWS_DYNAMO_TABLE_STATE_NAME
              value: "infra-deploy-state"
            - name: AWS_REGION
              value: "us-west-2"
            - name: PORT_APP
              value: "9090"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
