# Default values for efs-storage-class.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
metadata:
  name: efs-sc
parameters:                                                                                                                                                                                                             
  provisioningMode:  efs-ap
  fileSystemId: null
  directoryPerms: "700"
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true