apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/dns01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt  
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostName }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ .Values.name }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host:  {{ .Values.hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: 8080
        path: /github-webhook/
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: 8080
        path: /sonarqube-webhook/
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.hostName }}
    secretName: certmanager-tls        
