config:
  name: null
  dockerImage: null
  secretId: null
  secretAgent: null
  envName: null
  awsRegion: null
  tagVersion: null
  dbMigration: null

deployment: 
  replicas: 2
  resources:
    requests:
      cpu: 1000m
      memory: 2048M
    limits:
      cpu: 2000m
      memory: 3072M
  args: ["source /shared/sm/config/envvars && java -jar /app.jar"]
  nodeSelector: null
    
job:
  enabled: true
  name: null
  image: null
  version: null
  
ingress:
  className: nginx-public
  host: null
  externalDnsEnabled: false

hpa:
  enabled: false

sa:
  enabled: false
  awsRoleArn: null
  secretsClusterRoleEnabled: false


  
