{{- if .Values.volume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.config.name }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
{{- end }}