apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.name }}-service
  labels:
    app: {{ .Values.config.name }}
    env: {{ .Values.config.envName }}
    tag: {{ .Values.config.tagVersion }}
spec:
  selector:
{{ if .Values.lb.enabled }}
    type: LoadBalancer
{{ end }}
    app: {{ .Values.config.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
