config:
  name: null
  dockerImage: null
  secretId: null
  secretAgent: null
  envName: null
  awsRegion: null
  tagVersion: null

ingress:
  className: nginx-public
  host: null # example app_name.dev.brikl.com
  externalDnsEnabled: false

deployment:
  replicas: 1
  args: ["source /shared/sm/config/envvars && node server.js"]
  nodeSelector: null
    
sa:
  enabled: false
  awsRoleArn: null    