config:
  name: null
  dockerImage: null
  secretId: null
  secretAgent: null
  envName: null
  awsRegion: null
  tagVersion: null

ingress:
  className: nginx-public
  host: null # example app_name.dev.brikl.com
  externalDnsEnabled: false
  groupName: core-front
  albActive: true
  certifcateArn: "arn:aws:acm:us-west-2:xxxxxx:certificate/d3b474d2-a4b3-4ccb-a840-c207010137b8"

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2048M
    limits:
      cpu: 2000m
      memory: 3072M
  args: ["source /shared/sm/config/envvars && node server.js"]
  nodeSelector: null
    
sa:
  enabled: false
  awsRoleArn: null

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCpuUse: 50