apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.clusterConfig.ClusterName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    rabbitmq.com/operator-connection-uri: http://{{ .Values.clusterConfig.ClusterName }}.{{ .Release.Namespace }}.svc:15672
spec:
    replicas: {{ .Values.clusterConfig.replicaCount }}

{{- if .Values.secret }}
    secretBackend:
        externalSecret: 
            name: {{ .Values.clusterConfig.ClusterName }}-secret
{{- end }}
    persistence:
      storageClassName: {{ .Values.clusterConfig.storageClassName }}
      storage: {{ .Values.clusterConfig.storageSize }}

    rabbitmq:
      envConfig: |
        RABBITMQ_LOGS=""
      additionalConfig: |
        log.console = true
        log.console.level = debug
        log.console.formatter = json
        log.console.formatter.json.field_map = verbosity:v time msg domain file line pid level:-
        log.console.formatter.json.verbosity_map = debug:7 info:6 notice:5 warning:4 error:3 critical:2 alert:1 emergency:0
        log.console.formatter.time_format = epoch_usecs
        ssl_options.fail_if_no_peer_cert = false


    resources:
{{ if .Values.clusterConfig.resources }}
        {{- toYaml .Values.clusterConfig.resources | indent 6 }}
{{ end }}