{{- if .Values.secret }}
{{- $pass := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterConfig.ClusterName }}-secret
type: Opaque
stringData:
  default_user.conf: |
    default_user = {{ default "my-admin" .Values.secret.username }}
    default_pass = {{ $pass }}
  username: {{ default "my-admin" .Values.secret.username }}
  password: {{ $pass }}
  port: "5672"
  provider: rabbitmq
  type: rabbitmq
{{- end }}